# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cafe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cafe.proto',
  package='coffemachine',
  syntax='proto3',
  serialized_pb=_b('\n\ncafe.proto\x12\x0c\x63offemachine\x1a\x1bgoogle/protobuf/empty.proto\"R\n\nLatteOrder\x12 \n\x04size\x18\x01 \x01(\x0e\x32\x12.coffemachine.Size\x12\x13\n\x0btemperature\x18\x02 \x01(\r\x12\r\n\x05sugar\x18\x03 \x01(\r*K\n\x04Size\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x08\n\x04TINY\x10\x01\x12\t\n\x05SMALL\x10\x02\x12\n\n\x06MIDDLE\x10\x03\x12\t\n\x05LARGE\x10\x04\x12\n\n\x06XLARGE\x10\x05\x32P\n\rCoffeeMachine\x12?\n\tMakeLatte\x12\x18.coffemachine.LatteOrder\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_SIZE = _descriptor.EnumDescriptor(
  name='Size',
  full_name='coffemachine.Size',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TINY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMALL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIDDLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LARGE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XLARGE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=141,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_SIZE)

Size = enum_type_wrapper.EnumTypeWrapper(_SIZE)
DEFAULT = 0
TINY = 1
SMALL = 2
MIDDLE = 3
LARGE = 4
XLARGE = 5



_LATTEORDER = _descriptor.Descriptor(
  name='LatteOrder',
  full_name='coffemachine.LatteOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='coffemachine.LatteOrder.size', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='coffemachine.LatteOrder.temperature', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sugar', full_name='coffemachine.LatteOrder.sugar', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=139,
)

_LATTEORDER.fields_by_name['size'].enum_type = _SIZE
DESCRIPTOR.message_types_by_name['LatteOrder'] = _LATTEORDER
DESCRIPTOR.enum_types_by_name['Size'] = _SIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LatteOrder = _reflection.GeneratedProtocolMessageType('LatteOrder', (_message.Message,), dict(
  DESCRIPTOR = _LATTEORDER,
  __module__ = 'cafe_pb2'
  # @@protoc_insertion_point(class_scope:coffemachine.LatteOrder)
  ))
_sym_db.RegisterMessage(LatteOrder)



_COFFEEMACHINE = _descriptor.ServiceDescriptor(
  name='CoffeeMachine',
  full_name='coffemachine.CoffeeMachine',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=218,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeLatte',
    full_name='coffemachine.CoffeeMachine.MakeLatte',
    index=0,
    containing_service=None,
    input_type=_LATTEORDER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COFFEEMACHINE)

DESCRIPTOR.services_by_name['CoffeeMachine'] = _COFFEEMACHINE

# @@protoc_insertion_point(module_scope)
